---
require:
  - rubocop-performance
  - rubocop-rake
  # - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - bin/*
    - gemfiles/*
    - spec/**/*
    - lib/netbox-client-ruby.rb

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/AccessModifierDeclarations:
  Enabled: false

Layout/LineLength:
  Exclude:
    - lib/netbox_client_ruby/api/secrets/session_key.rb

# RSpec/NotToNot:
#   EnforcedStyle: to_not
