version: '2'
services:
  app:
    build:
      context: .
      args:
        RUBY_VERSION: 3.2.2
    image: netbox-client-ruby:3.2.2
    command: 'docker/start.test.sh'
  app27:
    build:
      context: .
      args:
        RUBY_VERSION: 2.7.8
    image: netbox-client-ruby:2.7.8
    command: 'docker/start.test.sh'
