version: '2'
services:
  nginx:
    image: nginx:1.14-alpine
    command: nginx -c /etc/netbox-nginx/nginx.conf
    depends_on:
      - netbox
    volumes:
      - netbox-nginx-config:/etc/netbox-nginx/
      - netbox-static-files:/opt/netbox/netbox/static
    ports:
      - 80:8080
  netbox:
    image: ninech/netbox:v2.4.3
    depends_on:
      - postgres
    volumes:
      - netbox-static-files:/opt/netbox/netbox/static
      - netbox-nginx-config:/etc/netbox-nginx/
    env_file: 'netbox.env'
  postgres:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD: netbox
      POSTGRES_DB: netbox
volumes:
  netbox-static-files:
    driver: local
  netbox-nginx-config:
    driver: local
